# Generated by Django 4.2.27 on 2025-12-20 03:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('area_rai', models.FloatField(default=0.0)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('province', models.CharField(blank=True, default='Phayao', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YieldEstimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_calculated', models.DateTimeField(auto_now_add=True)),
                ('ndvi_mean', models.FloatField()),
                ('estimated_yield_ton', models.FloatField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agriculture.ricefield')),
            ],
        ),
    ]
