# Generated by Django 4.2.27 on 2025-12-20 04:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ricefield',
            name='province',
        ),
        migrations.RemoveField(
            model_name='yieldestimation',
            name='date_calculated',
        ),
        migrations.AddField(
            model_name='yieldestimation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yieldestimation',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ricefield',
            name='area_rai',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ricefield',
            name='district',
            field=models.CharField(default='Phayao', max_length=100),
        ),
    ]
