# Generated by Django 5.2.9 on 2025-12-20 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0003_remove_ricefield_province_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yieldestimation',
            name='date',
        ),
        migrations.AddField(
            model_name='ricefield',
            name='variety',
            field=models.CharField(choices=[('KDML105', 'หอมมะลิ 105'), ('RD6', 'กข 6 (ข้าวเหนียว)'), ('RD15', 'กข 15'), ('PATHUM1', 'ปทุมธานี 1'), ('OTHER', 'อื่นๆ')], default='KDML105', max_length=20),
        ),
        migrations.CreateModel(
            name='SaleNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ton', models.FloatField(help_text='จำนวนตันที่ต้องการขาย')),
                ('price_per_ton', models.DecimalField(decimal_places=2, help_text='ราคาที่ต้องการ (บาท/ตัน)', max_digits=10)),
                ('phone', models.CharField(help_text='เบอร์ติดต่อ', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'รอรับซื้อ'), ('CLOSED', 'ขายแล้ว')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rice_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agriculture.ricefield')),
            ],
        ),
    ]
