# Generated by Django 5.2.9 on 2025-12-22 14:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0005_salenotification_buyer_salenotification_sold_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ricefield',
            unique_together={('owner', 'name')},
        ),
    ]
