# Generated by Django 5.2.9 on 2025-12-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0006_alter_ricefield_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='salenotification',
            name='buyer_contact',
            field=models.CharField(blank=True, help_text='เบอร์ติดต่อคนซื้อ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salenotification',
            name='phone',
            field=models.CharField(help_text='เบอร์ติดต่อชาวนา', max_length=20),
        ),
        migrations.AlterField(
            model_name='salenotification',
            name='status',
            field=models.CharField(choices=[('OPEN', 'รอรับซื้อ'), ('REQUESTED', 'รออนุมัติ'), ('SOLD', 'ขายแล้ว')], default='OPEN', max_length=20),
        ),
    ]
