# Generated by Django 5.2.9 on 2025-12-26 12:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0008_alter_ricefield_variety'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ricefield',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='ricefield',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ricefield',
            name='is_active',
            field=models.BooleanField(default=True, help_text='True=แสดงผล, False=ถูกลบ(Soft Delete)'),
        ),
        migrations.AddField(
            model_name='ricefield',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ricefield',
            name='area_rai',
            field=models.FloatField(default=0.0, help_text='พื้นที่ (ไร่)'),
        ),
        migrations.AlterField(
            model_name='ricefield',
            name='boundary',
            field=django.contrib.gis.db.models.fields.PolygonField(help_text='ขอบเขตแปลงนา (Polygon)', srid=4326),
        ),
        migrations.AlterField(
            model_name='ricefield',
            name='district',
            field=models.CharField(default='Phayao', help_text='อำเภอ', max_length=100),
        ),
        migrations.AlterField(
            model_name='ricefield',
            name='name',
            field=models.CharField(help_text='ชื่อแปลงนา', max_length=100),
        ),
        migrations.AlterField(
            model_name='ricefield',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rice_fields', to=settings.AUTH_USER_MODEL),
        ),
    ]
