# Generated by Django 5.2.9 on 2025-12-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0009_alter_ricefield_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salenotification',
            name='negotiated_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ราคาที่โรงสีต่อรอง', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ricefield',
            name='district',
            field=models.CharField(default='Phayao', help_text='จังหวัด/อำเภอ/ตำบล', max_length=100),
        ),
    ]
