# Generated by Django 5.2.9 on 2025-12-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0010_salenotification_negotiated_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ricefield',
            name='variety',
            field=models.CharField(choices=[('KDML105', 'หอมมะลิ 105'), ('RD6', 'กข 6 (ข้าวเหนียว)'), ('RD15', 'กข 15'), ('PATHUM1', 'ปทุมธานี 1'), ('OTHER', 'อื่นๆ')], default='KDML105', max_length=20),
        ),
    ]
