# Generated by Django 5.2.9 on 2026-01-03 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0011_alter_ricefield_variety'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ricefield',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_owner_name'),
        ),
    ]
