# Generated by Django 5.2.9 on 2026-01-05 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0012_ricefield_unique_owner_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salenotification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='salenotification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='salenotification',
            index=models.Index(fields=['status'], name='agriculture_status_3b507e_idx'),
        ),
        migrations.AddIndex(
            model_name='salenotification',
            index=models.Index(fields=['farmer', 'status'], name='agriculture_farmer__2bc8fb_idx'),
        ),
        migrations.AddIndex(
            model_name='salenotification',
            index=models.Index(fields=['created_at'], name='agriculture_created_291e39_idx'),
        ),
    ]
