# Generated by Django 4.2.27 on 2025-12-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FARMER', 'เกษตรกร'), ('MILLER', 'โรงสี/ผู้รับซื้อ'), ('GOVT', 'เจ้าหน้าที่รัฐ')], default='FARMER', max_length=10),
        ),
    ]
