# Generated by Django 5.2.9 on 2025-12-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_about_me_user_address_user_line_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ผู้ดูแลระบบ'), ('FARMER', 'เกษตรกร'), ('MILLER', 'โรงสี/ผู้รับซื้อ'), ('GOVT', 'เจ้าหน้าที่รัฐ')], default='FARMER', max_length=10),
        ),
    ]
